#ifndef INVALIDTOPPINGNAMEALREADYTAKENEXCEPTION_H
#define INVALIDTOPPINGNAMEALREADYTAKENEXCEPTION_H

class InvalidToppingNameAlreadyTakenException { };

#endif // INVALIDTOPPINGNAMEALREADYTAKENEXCEPTION_H
