#ifndef CONSTVALUES_H
#define CONSTVALUES_H

const int NUMBEROFVALUESINPIZZA = 7;
const int NUMBEROFVALUESINTYPE = 4;
const int NUMBEROFVALUESINTOPPING = 4;
const int NUMBEROFVALUESINDRINK = 4;
const int NUMBEROFVALUESINEXTRA = 4;

#endif // CONSTVALUES_H
