#ifndef INVALIDTYPENAMEBASICISRESERVEDEXCEPTION_H
#define INVALIDTYPENAMEBASICISRESERVEDEXCEPTION_H

class InvalidTypeNameBasicIsReservedException { };

#endif // INVALIDTYPENAMEBASICISRESERVEDEXCEPTION_H
